resilience4j.circuitbreaker:
    instances:
        myconfig2:
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 5
            waitDurationInOpenState: 10000
            failureRateThreshold: 30
            registerHealthIndicator: true
            record-exceptions:
            - org.springframework.web.client.HttpServerErrorException
            - org.springframework.web.client.HttpClientErrorException$TooManyRequests
            
